/**
 * Colaboraciones - relatos y obras de artistas.
 * Agregar artistas aqui + carpeta en collabs/<slug>/.
 */
window.COLLABS_CONTENT = {
  meta: {
    title: { es: "Colaboraciones | Rocio Mio", en: "Collaborations | Rocio Mio" },
  },
  nav: {
    volver: { es: "[ VOLVER AL ORIGEN ]", en: "[ BACK TO HOME ]" },
  },
  titulo: { es: "Colaboraciones", en: "Collaborations" },
  intro: {
    es: "Comentarios de artistas y entidades con los que ha colaborado Rocio Mio.",
    en: "Comments from artists and organizations who have collaborated with Rocio Mio.",
  },
  scrollHint: {
    es: "→ gira la rueda o usa las flechas",
    en: "→ scroll or use the arrows",
  },
  vacio: {
    es: "Pronto se agregaran obras de esta colaboracion.",
    en: "Works from this collaboration will be added soon.",
  },
  verEnIg: { es: "ver en instagram →", en: "view on instagram →" },
  prev: { es: "Imagen anterior", en: "Previous image" },
  next: { es: "Imagen siguiente", en: "Next image" },
};

// Artistas - id = carpeta en collabs/
window.COLLABS_ARTISTS = [
  {
    id: "ohde",
    nombre: "Clara Ohde",
    rol: {
      es: "Artista visual, disenadora industrial y docente - Argentina",
      en: "Visual artist, industrial designer and educator - Argentina",
    },
    texto: {
      es: "Rocio Mio es una artista y gestora multidisciplinaria. La caracteriza su capacidad para transformar una idea conceptual en un proyecto material. Tiene una mirada amplia y una facilidad poco comun para moverse entre distintos lenguajes y materiales: desde herramientas digitales, como codigo y glitch, recursos audiovisuales como fotografia, video y edicion, hasta tecnicas textiles, bordado, tintes naturales y confeccion. Tiene el habito de encontrar la forma de que cada recurso este al servicio de la idea.\n\nAdemas, cuenta con una gran capacidad de gestion y resolucion. Ha llevado adelante residencias artisticas y proyectos colectivos que requieren organizacion, adaptacion, compromiso y una gran capacidad para coordinar equipos, generar vinculos y desenvolverse en diferentes contextos. Su mirada integral le permite acompanar un proyecto desde su concepcion hasta su realizacion.\n\nMas alla de la infinidad de oficios y habilidades que domina, lo que mas destaco es su compromiso y perseverancia. Rocio trabaja con dedicacion, constancia y determinacion en todos los desafios que la vida le impone. Rendirse no es una opcion.\n\nSu confianza fue muy importante para mi desarrollo como artista. Tiene una sensibilidad especial para reconocer el potencial de otras personas, acompanarlas para desarrollarlo y, en especial, hacer que el mundo vea lo que ella ve.\n\nMi recomendacion hacia Rocio Mio es absoluta, tanto por su calidad humana como por su profesionalismo.",
      en: "Rocio Mio is a multidisciplinary artist and cultural manager. She is characterized by her ability to transform a conceptual idea into a material project. She has a wide-ranging vision and an uncommon ease moving between different languages and materials: from digital tools such as code and glitch, audiovisual resources like photography, video and editing, to textile techniques, embroidery, natural dyes and garment-making. She has the habit of finding ways for each resource to serve the idea.\n\nShe also has great management and problem-solving skills. She has led artistic residencies and collective projects that require organization, adaptation, commitment and a strong ability to coordinate teams, build relationships and navigate different contexts. Her integral vision allows her to accompany a project from conception to completion.\n\nBeyond the countless crafts and skills she masters, what I highlight most is her commitment and perseverance. Rocio works with dedication, consistency and determination through every challenge life presents. Giving up is not an option.\n\nHer trust was very important for my development as an artist. She has a special sensitivity for recognizing other people's potential, accompanying them to develop it and, above all, making the world see what she sees.\n\nMy recommendation of Rocio Mio is absolute, both for her human quality and her professionalism.",
    },
    instagram: {
      url: "https://www.instagram.com/ohde____/",
      etiqueta: "@ohde____",
    },
    obras: [
      { src: "ohde/collab ohde/Intersection_resized.webp", alt: "Intersection" },
      { src: "ohde/collab ohde/analogportal_resized.webp", alt: "Analog Portal" },
      { src: "ohde/collab ohde/cathartic ecoprint_resized.webp", alt: "Cathartic Ecoprint" },
      { src: "ohde/collab ohde/human fax 01_resized.webp", alt: "Human Fax 01" },
      { src: "ohde/collab ohde/human fax 02_resized.webp", alt: "Human Fax 02" },
      { src: "ohde/collab ohde/human fax 03_resized.webp", alt: "Human Fax 03" },
      { src: "ohde/collab ohde/human fax 04_resized.webp", alt: "Human Fax 04" },
      { src: "ohde/collab ohde/knittedpasta_resized.webp", alt: "Knitted Pasta" },
      { src: "ohde/20240520_162124_resized.webp", alt: "Proceso en residencia" },
      { src: "ohde/20240522_224147_resized.webp", alt: "Proceso en residencia" },
      { src: "ohde/20240523_153925_resized.webp", alt: "Proceso en residencia" },
      { src: "ohde/20240525_142856_resized.webp", alt: "Proceso en residencia" },
      { src: "ohde/20240529_153446_resized.webp", alt: "Proceso en residencia" },
      { src: "ohde/IMG_9701_resized.webp", alt: "Proceso en residencia" },
    ],
  },
  {
    id: "ale-piovano",
    nombre: "Ale Piovano",
    rol: {
      es: "Artista · fotografia y proyectos colaborativos",
      en: "Artist · photography and collaborative projects",
    },
    texto: {
      es: "He trabajado con Rocio Mio en dos proyectos artisticos y tambien participe en uno de los talleres de arte que ella y su pareja daban en forma de residencia artistica en Bosque Gracias antes del desvastador incendio que les toco vivir.\n\nEl primer proyecto artistico que hicimos juntas fue un libro unico fotografico que en lo personal resulto una joya absoluta, yo sacaba fotos pero no tenia la menor idea de como se hacia un libro, Rocio Mio se involucro y creo un objeto de una belleza total y vanguardista.\n\nPara el segundo proyecto fuimos invitadas por una curadora para hacer un proyecto artistico y ecologico y creamos una especie de mapa de los humedales ribereños del Lago Epuyen hecho con pequenas piezas de arte y fotografias al que llamamos \"Mapeo Artistico Ribereno\" y que fue presentado en el museo de arte contemporaneo de Santa Fe.\n\nPor ultimo, tambien participe de una de sus residencias artisticas y lo que vi alli fue profesionalismo y una entrega absoluta y sobre todo un grupo de gente feliz de haber elegido esa residencia y participar.",
      en: "I have worked with Rocio Mio on two artistic projects and also took part in one of the art workshops that she and her partner offered as an artistic residency at Bosque Gracias before the devastating fire they went through.\n\nThe first artistic project we did together was a unique photographic book that, personally, turned out to be an absolute jewel. I took photos but had no idea how to make a book; Rocio Mio got involved and created an object of total and avant-garde beauty.\n\nFor the second project we were invited by a curator to make an artistic and ecological project, and we created a kind of map of the riverside wetlands of Lake Epuyen made with small art pieces and photographs, which we called \"Mapeo Artistico Ribereno\" and which was presented at the contemporary art museum of Santa Fe.\n\nFinally, I also took part in one of her artistic residencies, and what I saw there was professionalism and absolute dedication, and above all a group of people happy to have chosen that residency and to take part.",
    },
    // Imagenes horizontales - webp livianos en Ale piovano/webp/
    obras: [
      { src: "Ale piovano/webp/presentacion para video impr3.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr4.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr5.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr6.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr7.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr8.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr9.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr10.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr11.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr12.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr13.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr14.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr15.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr16.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr17.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr18.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr19.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr20.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr21.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr22.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr23.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr24.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr25.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr26.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr27.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr28.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr29.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr30.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr31.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr32.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr33.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr34.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr35.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr36.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr37.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr38.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr39.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr40.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr41.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr42.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr43.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr44.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr45.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr46.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr47.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr48.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr49.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr50.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr51.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr52.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr53.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr54.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr55.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr56.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr57.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr58.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr59.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr60.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr61.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr62.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr63.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr64.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr65.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr66.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr67.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr68.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr69.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr70.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr71.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr72.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr73.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr74.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr75.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr76.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr77.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr78.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr79.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr80.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr81.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr82.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr83.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr84.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr85.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr86.webp", alt: "Mapeo Artistico Ribereno" },
      { src: "Ale piovano/webp/presentacion para video impr87.webp", alt: "Mapeo Artistico Ribereno" },
    ],
  },
  {
    id: "jade-sivori",
    nombre: "Jade Sivori",
    rol: {
      es: "Fotografa y gestora de la residencia Gaia Refugio",
      en: "Photographer and manager of Gaia Refugio residency",
    },
    texto: {
      es: "Rocio Mio parece ser una fuente inagotable de creatividad y energia. Tanto en proyectos relacionados con textiles, obras de arte, dictando talleres presenciales, proponiendo actividades entre otras muchas muchas cosas.\n\nCabe destacar que ese compromiso en el campo artistico no quita el ambiental. Sus proyectos suelen estar atravesados por el respeto al ambiente, como por ejemplo podemos ver en los textiles tenidos con plantas, el reciclaje tanto de prendas de ropa como de papeles o la utilizacion de tecnologia \"obsoleta\" para crear nuevas obras de arte.",
      en: "Rocio Mio seems to be an inexhaustible source of creativity and energy. Both in projects related to textiles, artworks, leading in-person workshops, proposing activities, among many many other things.\n\nIt is worth noting that this commitment in the artistic field does not leave out the environmental. Her projects are often crossed by respect for the environment, as we can see for example in textiles dyed with plants, the recycling of both clothing and papers, or the use of \"obsolete\" technology to create new artworks.",
    },
    instagram: {
      url: "https://www.instagram.com/jade.sivori/",
      etiqueta: "@jade.sivori",
    },
    obras: [],
  },
  {
    id: "teztones",
    nombre: "Teztones",
    rol: {
      es: "Hashbrown · Teztones · United States",
      en: "Hashbrown · Teztones · United States",
    },
    texto: {
      es: "TezTones es una liga deportiva para artistas. Exploramos como la colaboracion y la competencia pueden cruzarse con las artes asignando artistas a un equipo para crear una pieza colaborativa a partir de un tema comun en cada partido.\n\nRocio es una persona maravillosa para trabajar! Tiene una vision artistica fuerte y aporta mucho creativamente, pero tambien es muy abierta de mente y buena encontrando puntos en comun al colaborar. Tanto como artista como organizadora aporta una dualidad de energia contagiosa y una presencia calmada y estable. Eso, sumado a una buena etica de trabajo y habilidades de comunicacion, la convierten en una gema absoluta!",
      en: "TezTones is a sports league for artists. We are exploring how collaboration and competition can intersect with the arts by assigning artists to a team to create a collaborative piece off of a common theme each match.\n\nRocio is a wonderful person to work with! She has a strong artistic vision and brings a lot to the table creatively, but is also very open minded and good at finding common ground when collaborating. Both as an artist and organizer she brings a duality of infectious energy and a calm grounding presence. That on top of a good work ethic and communication skills make her an absolute gem!",
    },
    obras: [
      {
        type: "youtube",
        src: "18o7peQXFII",
        alt: "Teztones · YouTube Shorts",
      },
    ],
  },
];

window.PAGE_I18N_CONTENT = window.COLLABS_CONTENT;
